openapi: 3.0.0

info:
  title: User Service API
  description: Event-driven User Registration API using RabbitMQ
  version: 1.0.0

servers:
  - url: http://localhost:3000/

paths:
  /api/v1/user/register:
    post:
      summary: Register a new user
      description: Publishes USER_REGISTERED event to RabbitMQ
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              properties:
                name:
                  type: string
                  example: Rahul
                email:
                  type: string
                  example: rahul@gmail.com
      responses:
        201:
          description: User event published successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered event published
        500:
          description: Server error
